typography_spectrum: 0.9547125606331974
color:
  brandStrength: 0.22726655914448202
  lightness: 0.8108868468552828
  saturation: 0.27522310172207654
  rhythmicContrast: 0.48978723282925785
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.9481845512054861
name: PattlezMusic
navigation:
  - name: Facebook Page
    url: 'https://www.facebook.com/PattlezMusic'
    type: external
  - name: SoundCloud
    url: 'https://soundcloud.com/pattlez'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/PattlezOfficial'
    type: external
title: The Misadventures of Pattlez
description: '"Who said zeroes, can''t become heroes?"'
